# Déploiement beta Next.js sur Netlify
# https://docs.netlify.com/frameworks/next-js/overview/

[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"
